<template>
  <section>
    <h2>Portfolio</h2>
    <div class="portfolio">
      <div v-for="project in projects" :key="project.name" class="portfolio-teaser">
        <img :src="project.image" :alt="project.name + ' teaser'">
        <h3>{{ project.name }}</h3>
        <p>{{ project.description }}</p>
        <a :href="project.link" target="_blank">See on GitHub</a>
      </div>
    </div>
  </section>
</template>

<script>
import jsdocTemplateImage from '@/assets/projects/jsdoc-template.png';
import comandanteImage from '@/assets/projects/comandante.png';
import youtubeDownloaderImage from '@/assets/projects/youtube-downloader.png';

export default {
  name: 'AppPortfolio',
  data() {
    return {
      projects: [
        {
          name: 'jsdoc-template',
          description: 'Accept JSON data generated by the JSDoc "explain" command as input and present it in a responsive website that is user-friendly and easy to navigate.',
          image: jsdocTemplateImage,
          link: 'https://github.com/germanbisurgi/jsdoc-template'
        },
        {
          name: 'commandante',
          description: 'Comandante is an Electron-based UI that allows you to execute command line commands with ease.',
          image: comandanteImage,
          link: 'https://github.com/germanbisurgi/comandante'
        },
        {
          name: 'youtube-downloader',
          description: 'Electron application that serves as a user interface (UI) for yt-dlp, offering various features for downloading videos and playlists, as well as extracting audio (mp3) from both single videos and playlists.',
          image: youtubeDownloaderImage,
          link: 'https://github.com/germanbisurgi/youtube-downloader'
        }
      ]
    }
  }
}
</script>
